    - name: Installing Nginx
      package:
       name: "nginx"
       state: present
       update_cache: yes
    - name: delete default config file
      file:
        path: /etc/nginx/sites-available/default
        state: absent
    - name: Nginx config file copy
      template:
        src: "nginx.conf"
        dest: "/etc/nginx/sites-available/default"
        owner: root
        group: root
        mode: 0644
    - name: Nginx config file symlink
      file:
        state: link
        src: "/etc/nginx/sites-available/default"
        dest: "/etc/nginx/sites-enabled/default"
        owner: root
        group: root
        mode: 0644
    - name: stoping apache2 server    
      service:
        name: apache2
        state: stopped
    - name: start and enable mysql service    
      service:
        name: nginx
        state: started
        enabled: yes